#130: When users run any command less-cli should check the last versi…
chuva-io/less-cli pull request #131
Opened 2024-10-03 10:44 UTC by Lolneilor

2024-10-03 10:48 UTC, RicardoJRR-23 submitted a review, later dismissed

2024-10-03 11:08 UTC, vandro commented on bin/index.js
> +        process.exit(0);
Like this it will always indicates Success, I think you should check if the command was executed successfully or with error exit with `0` or `1`

2024-10-03 11:09 UTC, vandro requested changes
See my comment.

2024-10-09 14:47 UTC, RicardoJRR-23 submitted a review, later dismissed

2024-10-09 14:50 UTC, RonyGomesK78 approved these changes

2024-10-09 15:14 UTC, RonyGomesK78 approved these changes

2024-10-09 15:15 UTC, vandro approved these changes

2024-10-09 15:15 UTC, merged