#133: Update the exit command execution
chuva-io/less-cli pull request #134
Opened 2024-10-08 13:31 UTC by Lolneilor

Update the exit command execution to utilize exitCode instead of process.exit. This change aligns with the adaptation related to #130 . With this update, the  message will be displayed only after the command has fully completed its execution.

2024-10-08 16:11 UTC, RicardoJRR-23 submitted a review, later dismissed

2024-10-09 12:09 UTC, vandro requested changes
Please see my comments.

2024-10-09 12:09 UTC, vandro commented on commands/user/create_account.js
This file changes are not related to this scope.

2024-10-09 12:09 UTC, vandro commented on commands/user/create_session.js
> -  inquirer.prompt(questions).then(async (answers) => await login(answers));
This change is not related to this scope.

2024-10-09 12:09 UTC, vandro commented on commands/helpers/handle_error.js
>  export default function handleError(message) {
Please verify where this is being called and check if there is a `finally` on the try catch.

2024-10-09 12:12 UTC, vandro commented
Please change the version on `package.json`

2024-10-09 13:41 UTC, RonyGomesK78 submitted a review, later dismissed

2024-10-09 13:41 UTC, RonyGomesK78 commented on commands/helpers/credentials.js
> -      process.exit(1);
you forgot to add the `process.exitCode=1`

2024-10-09 13:51 UTC, RonyGomesK78 approved these changes

2024-10-09 14:01 UTC, vandro approved these changes

2024-10-09 15:06 UTC, RonyGomesK78 approved these changes

2024-10-09 15:08 UTC, merged