#132:Show the user the Dashboard URL for their project after a successful deployment
chuva-io/less-cli pull request #135
Opened 2024-10-09 16:24 UTC by Lolneilor

2024-10-10 09:32 UTC, vandro approved these changes

2024-10-10 09:36 UTC, RonyGomesK78 approved these changes

2024-10-10 09:38 UTC, RonyGomesK78 approved these changes

2024-10-10 09:58 UTC, vandro commented on bin/index.js
> +        console.log(`\nYou can visit https://dashboard.less.chuva.io/projects/${project_name} to view your projects resources, logs, and metrics from your browser.`);
This Should not show for static deploy.

2024-10-10 09:59 UTC, vandro requested changes
@Lolneilor please see my comment.

2024-10-10 11:38 UTC, vandro approved these changes

2024-10-10 11:41 UTC, RicardoJRR-23 submitted a review, later dismissed

2024-10-11 12:29 UTC, vandro approved these changes

2024-10-11 12:31 UTC, vandro approved these changes

2024-10-11 12:33 UTC, RicardoJRR-23 approved these changes

2024-10-11 12:34 UTC, merged