#1: Add CLI command that creates template code for a shared MongoDB client in JS
chuva-io/less-cli pull request #14
Opened 2023-09-11 20:11 UTC by nnascim

2023-09-11 20:29 UTC, FabyoSK commented on commands/add-template/create/mongodb_js_shared_client.js
Please consider using async/await for FileSystem operations, it will prevent the main thread to be blocked and you will have the ability to copy multiple files at once using `Promise.all`

2023-09-11 20:42 UTC, nnascim commented on commands/add-template/create/mongodb_js_shared_client.js
Thank you. If there are no other comments I'll make this a separate issue.

2023-09-12 10:20 UTC, FredSoares requested changes

2023-09-12 10:20 UTC, FredSoares commented on template_code/js/mongodb_js_shared_client/basic_crud_helpers/index.js
> +
@nnascim Looks like you forgot the update function

2023-09-12 19:39 UTC, nnascim commented on commands/add-template/create/mongodb_js_shared_client.js
@FabyoSK I've created a new issue for this.

2023-09-12 19:40 UTC, nnascim commented on template_code/js/mongodb_js_shared_client/basic_crud_helpers/index.js
> +
I did not intend to add it. I also deleted the `delete` function.

2023-09-12 20:59 UTC, FabyoSK approved these changes

2023-09-13 10:11 UTC, FredSoares approved these changes

2023-09-13 10:12 UTC, merged