Update commands to replace old routes to news API routes
chuva-io/less-cli pull request #94
Opened 2024-02-16 13:49 UTC by FredSoares

fix: #93

2024-02-16 15:31 UTC, RonyGomesK78 requested changes

2024-02-16 15:31 UTC, RonyGomesK78 commented on service/selectOrganization.js
> +  let orgId
you forgot the semicolon

2024-02-16 15:31 UTC, RonyGomesK78 commented on service/selectOrganization.js
> +    const organizations = await fetchOrganizations();
this code is not idented

2024-02-16 17:30 UTC, kaffonso commented on commands/projects/deploy/index.js
> +import { authorizedPost} from '../../../service/authorizedRequests.js';
@FredSoares add space after the `authorizedPost`

2024-03-05 11:45 UTC, kaffonso approved these changes

2024-03-05 12:01 UTC, MDRRicardo approved these changes

2024-03-05 12:02 UTC, savylopes approved these changes

2024-03-05 12:03 UTC, RicardoJRR-23 approved these changes

2024-03-05 16:15 UTC, merged